[package]
name = "dev-runtime"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "devrun"
path = "src/main.rs"

[dependencies]
dev-syntax = { path = "../syntax" }
libffi = "5"
libloading = "0.8"
serde_json = { version = "1", features = ["arbitrary_precision"] }
ureq = { version = "3.4.2", default-features = false, features = ["rustls", "gzip"] }
tiny_http = "0.12"
url = "2"
base64 = "0.23"
chrono = { version = "0.4", default-features = false, features = ["std", "now"] }
getrandom = "0.2"
regex = "1"
encoding_rs = "0.8"
sha2 = "0.10"
hmac = "0.12"
subtle = "2"
aes-gcm = "0.10"
flate2 = "1"
zip = { version = "9", default-features = false, features = ["deflate-flate2"] }
tar = "0.4"
uuid = "1"
command-group = "5"
rusqlite = { version = "0.40", features = ["bundled", "extra_check", "hooks", "limits"] }
csv = "1"
toml = "0.9"
serde-saphyr = "1"
serde = "1"
rustls = { version = "0.23", default-features = false, features = ["std", "ring", "tls12"] }
rustls-pemfile = "2"
webpki-roots = "1"
tungstenite = { version = "0.30", default-features = false, features = ["handshake"] }
pathdiff = "0.2"
sysinfo = { version = "0.37", default-features = false, features = ["system"] }
