[package]
name = "dev-runtime"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "devrun"
path = "src/main.rs"

[dependencies]
dev-syntax = { path = "../syntax" }
libffi = "5"
libloading = "0.8"
serde_json = { version = "1", features = ["arbitrary_precision"] }
ureq = { version = "3.4.2", default-features = false, features = ["rustls", "gzip"] }
tiny_http = "0.12"
url = "2"
base64 = "0.23"
pathdiff = "0.2"
sysinfo = { version = "0.37", default-features = false, features = ["system"] }
